# Generated by Django 3.2.22 on 2023-10-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_auto_20231015_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
